// This file is auto-generated by a script. Do not edit.

import { type User } from '@frontend/types/user';
import { type UserCreate } from '@frontend/types/user_create';

export interface AccountBase {
  username: string;
  image?: string | null;
  provider: string;
  provider_account_id: string;
  user_id?: number | null;
}

export interface Account extends AccountBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  password?: string | null;
  user?: User | null;
}

export interface AccountCreate extends AccountBase {
  user_id?: number | null;
  password?: string | null;
}

export interface AccountLoad extends AccountBase {
  id: number;
  created_at: string;
  updated_at: string;
}

export interface AccountSignInWithCredentials {
  email: string;
  password: string;
}

export interface AccountSignInWithOauth {
  provider: string;
  provider_account_id: string;
  user: UserCreate;
}

export interface AccountSignUpWithCredentials {
  name: string;
  username: string;
  email: string;
  password: string;
}

export interface AccountUpdate {
  password?: string | null;
}
