// This file is auto-generated by a script. Do not edit.

import { type Question } from '@frontend/types/question';
import { type User } from '@frontend/types/user';

export interface AnswerBase {
  content: string;
  user_id: number;
  question_id: number;
  upvotes?: number | null;
  downvotes?: number | null;
}

export interface Answer extends AnswerBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  user: User;
  question: Question;
}

export type AnswerCreate = AnswerBase;

export interface AnswerLoad extends AnswerBase {
  id: number;
  created_at: string;
  updated_at: string;
}

export type AnswerUpdate = object;
