// This file is auto-generated by a script. Do not edit.

export enum QuestionCount {
  BRONZE = "10",
  SILVER = "50",
  GOLD = "100",
}

export enum AnswerCount {
  BRONZE = "10",
  SILVER = "50",
  GOLD = "100",
}

export enum QuestionUpvotes {
  BRONZE = "10",
  SILVER = "50",
  GOLD = "100",
}

export enum AnswerUpvotes {
  BRONZE = "10",
  SILVER = "50",
  GOLD = "100",
}

export enum TotalViews {
  BRONZE = "1000",
  SILVER = "10000",
  GOLD = "100000",
}

export interface Badges {
  gold: number;
  silver: number;
  bronze: number;
}
