// This file is auto-generated by a script. Do not edit.

export enum ActionContentType {
  QUESTION = "question",
  ANSWER = "answer",
  TAG = "tag",
}

export enum ActionType {
  VIEW = "view",
  UPVOTE = "upvote",
  DOWNVOTE = "downvote",
  BOOKMARK = "bookmark",
  POST = "post",
  EDIT = "edit",
  DELETE = "delete",
  SEARCH = "search",
}

export enum ActionPoints {
  NONE = "0",
  VIEW = "0",
  UPVOTE_CURRENT_USER = "2",
  UPVOTE_OWNER = "10",
  BOOKMARK_CURRENT_USER = "0",
  BOOKMARK_OWNER = "1",
  POST_QUESTION = "5",
  POST_ANSWER = "10",
}

export type InteractionBase = object;

export interface Interaction extends InteractionBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  user_id: number;
  content_type: ActionContentType;
  target_id: number;
  action_type: ActionType;
  points: number;
  other_user_id?: number | null;
  other_points?: number | null;
}

export interface InteractionCreate extends InteractionBase {
  user_id: number;
  content_type: ActionContentType;
  target_id: number;
  action_type: ActionType;
}

export interface InteractionLoad extends InteractionBase {
  id: number;
  created_at: string;
  updated_at: string;
  user_id: number;
  content_type: ActionContentType;
  target_id: number;
  action_type: ActionType;
  points: ActionPoints;
  other_user_id?: number | null;
  other_points: ActionPoints;
}

export type InteractionUpdate = object;
