// This file is auto-generated by a script. Do not edit.

import { type Answer, type AnswerLoad } from '@/types/answer';
import { type Tag, type TagLoad } from '@/types/tag';
import { type User, type UserLoad } from '@/types/user';

export interface QuestionBase {
  title: string;
  content: string;
  views?: number | null;
  upvotes?: number | null;
  downvotes?: number | null;
  author_id: number;
}

export interface Question extends QuestionBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  answers?: Answer[] | null;
  tags: Tag[];
  author?: User | null;
}

export interface QuestionCreate {
  title: string;
  content: string;
  tags: string[];
  author_id: number;
}

export interface QuestionLoad extends QuestionBase {
  id: number;
  created_at: string;
  updated_at: string;
  tags?: TagLoad[] | null;
  author: UserLoad;
  answers?: AnswerLoad[] | null;
}

export interface QuestionUpdate {
  id: number;
  title: string;
  content: string;
  tags: string[];
  author_id: number;
}

export interface QuestionTagRelationship {
  question_id: number;
  tag_id: number;
}
