// This file is auto-generated by a script. Do not edit.

import { type Answer } from '@frontend/types/answer';
import { type AnswerLoad } from '@frontend/types/answer_load';
import { type Tag } from '@frontend/types/tag';
import { type TagLoad } from '@frontend/types/tag_load';
import { type User } from '@frontend/types/user';
import { type UserLoad } from '@frontend/types/user_load';

export interface QuestionBase {
  title: string;
  content: string;
  views?: number | null;
  upvotes?: number | null;
  downvotes?: number | null;
  author_id: number;
}

export interface Question extends QuestionBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  answers?: Answer[] | null;
  tags: Tag[];
  author?: User | null;
}

export interface QuestionCreate {
  title: string;
  content: string;
  tags: string[];
  author_id: number;
}

export interface QuestionLoad extends QuestionBase {
  id: number;
  created_at: string;
  updated_at?: string | null;
  tags?: TagLoad[] | null;
  author?: UserLoad | null;
  answers?: AnswerLoad[] | null;
  views?: number | null;
}

export interface QuestionUpdate {
  id: number;
  title?: string | null;
  content?: string | null;
  tags?: string[] | null;
  author_id?: number | null;
  views?: number | null;
}

export interface QuestionTagRelationship {
  question_id: number;
  tag_id: number;
}
