// This file is auto-generated by a script. Do not edit.

import { type Account } from '@frontend/types/account';
import { type Answer } from '@frontend/types/answer';
import { type Question } from '@frontend/types/question';
import { type UserCollection } from '@frontend/types/user_collection';

export interface UserBase {
  name: string;
  username: string;
  email: string;
  bio?: string | null;
  image: string;
  location?: string | null;
  portfolio?: string | null;
  reputation?: number | null;
}

export interface User extends UserBase {
  id?: number | null;
  created_at: string;
  updated_at?: string | null;
  accounts?: Account[] | null;
  questions?: Question[] | null;
  answers?: Answer[] | null;
  collection?: UserCollection[] | null;
}

export type UserCreate = UserBase;

export interface UserLoad extends UserBase {
  id: number;
  created_at: string;
  updated_at?: string | null;
}

export type UserUpdate = object;
