// This file is auto-generated by a script. Do not edit.

import { type Question } from '@frontend/types/question';
import { type User } from '@frontend/types/user';

export type UserCollectionBase = object;

export interface UserCollection {
  created_at: string;
  updated_at?: string | null;
  user_id: number;
  question_id: number;
  user: User;
  question: Question;
}

export interface UserCollectionCreate extends UserCollectionBase {
  user_id: number;
  question_id: number;
}

export interface UserCollectionLoad extends UserCollectionBase {
  created_at: string;
  updated_at: string;
  user_id: number;
  question_id: number;
}

export type UserCollectionUpdate = object;
