// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/apiFetch';
import { ActionResponse } from '@/types/global';
import { type AccountCreate, AccountLoad, AccountSignInWithOauth, AccountUpdate } from '@/types/account';

export const apiAccount = {
  getAccount: (accountId: number): Promise<ActionResponse<AccountLoad>> =>
    fetchHandler(`/api/v1/account/load/${accountId}`),

  create: (account: AccountCreate): Promise<ActionResponse<AccountLoad>> =>
    fetchHandler(`/api/v1/account/create`, {
      method: "POST",
      body: JSON.stringify(account)
    }),

  update: (accountId: number, account_update: AccountUpdate): Promise<ActionResponse<AccountLoad>> =>
    fetchHandler(`/api/v1/account/update/${accountId}`, {
      method: "PUT",
      body: JSON.stringify(account_update)
    }),

  delete: (accountId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/account/delete/${accountId}`, {
      method: "DELETE"
    }),

  loadByProviderAccountId: (provider: string): Promise<ActionResponse<AccountLoad>> =>
    fetchHandler(`/api/v1/account/provider`, {
      method: "POST",
      body: JSON.stringify(provider)
    }),

  signInWithOauth: (account_with_oauth: AccountSignInWithOauth): Promise<ActionResponse<AccountLoad>> =>
    fetchHandler(`/api/v1/account/sign-in-with-oauth`, {
      method: "POST",
      body: JSON.stringify(account_with_oauth)
    }),
};
