// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type AnswerCreate, AnswerLoad, AnswerUpdate } from '@/types/answer';

export const apiAnswer = {
  getAnswer: (answerId: number): Promise<ActionResponse<AnswerLoad>> =>
    fetchHandler(`/api/v1/answer/load/${answerId}`),

  create: (answer: AnswerCreate): Promise<ActionResponse<AnswerLoad>> =>
    fetchHandler(`/api/v1/answer/create`, {
      method: "POST",
      body: JSON.stringify(answer)
    }),

  update: (answerId: number, answer_update: AnswerUpdate): Promise<ActionResponse<AnswerLoad>> =>
    fetchHandler(`/api/v1/answer/update/${answerId}`, {
      method: "PUT",
      body: JSON.stringify(answer_update)
    }),

  delete: (answerId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/answer/delete/${answerId}`, {
      method: "DELETE"
    }),

  getAnswersForQuestion: (questionId: number, page: number, pageSize: number): Promise<ActionResponse<AnswerLoad[]>> => {
    const params = new URLSearchParams();
    if (page !== undefined && page !== null) params.append('page', page.toString());
    if (pageSize !== undefined && pageSize !== null) params.append('page_size', pageSize.toString());
    return fetchHandler(`/api/v1/answer/answers-for-question/${questionId}?${params.toString()}`);
  },
};
