// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type Badges } from '@/types/badges';

export const apiBadges = {
  getUserBadges: (userId: number): Promise<ActionResponse<Badges>> =>
    fetchHandler(`/api/v1/badges/user-badges/${userId}`),
};
