// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type InteractionCreate } from '@/types/interaction';

export const apiInteraction = {
  create: (interaction: InteractionCreate): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/interaction/create`, {
      method: "POST",
      body: JSON.stringify(interaction)
    }),
};
