// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/apiFetch';
import { ActionResponse } from '@/types/global';
import { type QuestionCreate, QuestionLoad, QuestionUpdate } from '@/types/question';

export const apiQuestion = {
  getQuestion: (questionId: number): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/load/${questionId}`),

  create: (question: QuestionCreate): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/create`, {
      method: "POST",
      body: JSON.stringify(question)
    }),

  update: (questionId: number, question_update: QuestionUpdate): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/update/${questionId}`, {
      method: "PUT",
      body: JSON.stringify(question_update)
    }),

  delete: (questionId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/question/delete/${questionId}`, {
      method: "DELETE"
    }),
};
