// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type QuestionCreate, QuestionLoad, QuestionUpdate } from '@/types/question';

export const apiQuestion = {
  getQuestion: (questionId: number): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/load/${questionId}`),

  create: (question: QuestionCreate): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/create`, {
      method: "POST",
      body: JSON.stringify(question)
    }),

  update: (questionId: number, question_update: QuestionUpdate): Promise<ActionResponse<QuestionLoad>> =>
    fetchHandler(`/api/v1/question/update/${questionId}`, {
      method: "PUT",
      body: JSON.stringify(question_update)
    }),

  delete: (questionId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/question/delete/${questionId}`, {
      method: "DELETE"
    }),

  getQuestions: (page: number, pageSize: number, query: string, filter: string): Promise<ActionResponse<QuestionLoad[]>> => {
    const params = new URLSearchParams();
    if (page !== undefined && page !== null) params.append('page', page.toString());
    if (pageSize !== undefined && pageSize !== null) params.append('page_size', pageSize.toString());
    if (query) params.append('query', query);
    if (filter) params.append('filter', filter);
    return fetchHandler(`/api/v1/question/questions?${params.toString()}`);
  },
};
