// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from "@/lib/handlers/apiFetch";
import { ActionResponse } from "@/types/global";
import { type TagCreate, TagLoad, TagUpdate } from "@/types/tag";

export const apiTag = {
  getTag: (tagId: number): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/load/${tagId}`),

  create: (tag: TagCreate): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/create`, {
      method: "POST",
      body: JSON.stringify(tag),
    }),

  update: (
    tagId: number,
    tag_update: TagUpdate
  ): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/update/${tagId}`, {
      method: "PUT",
      body: JSON.stringify(tag_update),
    }),

  delete: (tagId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/tag/delete/${tagId}`, {
      method: "DELETE",
    }),
};
