// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type TagCreate, TagLoad, TagUpdate } from '@/types/tag';

export const apiTag = {
  getTag: (tagId: number): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/load/${tagId}`),

  create: (tag: TagCreate): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/create`, {
      method: "POST",
      body: JSON.stringify(tag)
    }),

  update: (tagId: number, tag_update: TagUpdate): Promise<ActionResponse<TagLoad>> =>
    fetchHandler(`/api/v1/tag/update/${tagId}`, {
      method: "PUT",
      body: JSON.stringify(tag_update)
    }),

  delete: (tagId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/tag/delete/${tagId}`, {
      method: "DELETE"
    }),

  getTags: (page: number, pageSize: number, query: string, filter: string): Promise<ActionResponse<TagLoad[]>> => {
    const params = new URLSearchParams();
    if (page !== undefined && page !== null) params.append('page', page.toString());
    if (pageSize !== undefined && pageSize !== null) params.append('page_size', pageSize.toString());
    if (query) params.append('query', query);
    if (filter) params.append('filter', filter);
    return fetchHandler(`/api/v1/tag/tags?${params.toString()}`);
  },

  getTagQuestions: (tagId: number, page: number, pageSize: number, query: string, filter: string): Promise<ActionResponse<void>> => {
    const params = new URLSearchParams();
    if (page !== undefined && page !== null) params.append('page', page.toString());
    if (pageSize !== undefined && pageSize !== null) params.append('page_size', pageSize.toString());
    if (query) params.append('query', query);
    if (filter) params.append('filter', filter);
    return fetchHandler(`/api/v1/tag/${tagId}/questions?${params.toString()}`);
  },
};
