// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type UserCollectionLoad } from '@/types/user_collection';

export const apiUserCollection = {
  getUserCollection: (userId: number, questionId: number): Promise<ActionResponse<UserCollectionLoad>> =>
    fetchHandler(`/api/v1/user_collection/load/${userId}/${questionId}`),

  toggle: (userId: number, questionId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/user_collection/toggle/${userId}/${questionId}`, {
      method: "POST"
    }),
};
