// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type UserCreate, UserLoad, UserUpdate } from '@/types/user';

export const apiUser = {
  getAll: (): Promise<ActionResponse<UserLoad[]>> =>
    fetchHandler(`/api/v1/user`),

  loadByEmail: (email: string): Promise<ActionResponse<UserLoad>> => {
    const params = new URLSearchParams();
    if (email) params.append('email', email);
    return fetchHandler(`/api/v1/user/email?${params.toString()}`, {
      method: "POST"
    });
  },

  loadByUsername: (username: string): Promise<ActionResponse<UserLoad>> => {
    const params = new URLSearchParams();
    if (username) params.append('username', username);
    return fetchHandler(`/api/v1/user/username?${params.toString()}`, {
      method: "POST"
    });
  },

  getUser: (userId: number): Promise<ActionResponse<UserLoad>> =>
    fetchHandler(`/api/v1/user/load/${userId}`),

  create: (user: UserCreate): Promise<ActionResponse<UserLoad>> =>
    fetchHandler(`/api/v1/user/create`, {
      method: "POST",
      body: JSON.stringify(user)
    }),

  update: (userId: number, user_update: UserUpdate): Promise<ActionResponse<UserLoad>> =>
    fetchHandler(`/api/v1/user/update/${userId}`, {
      method: "PUT",
      body: JSON.stringify(user_update)
    }),

  delete: (userId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/user/delete/${userId}`, {
      method: "DELETE"
    }),
};
