// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/apiFetch';
import { ActionResponse } from '@/types/global';
import { type VoteCreate, VoteLoad, VoteUpdate } from '@/types/vote';

export const apiVote = {
  getVote: (voteId: number): Promise<ActionResponse<VoteLoad>> =>
    fetchHandler(`/api/v1/vote/load/${voteId}`),

  create: (vote: VoteCreate): Promise<ActionResponse<VoteLoad>> =>
    fetchHandler(`/api/v1/vote/create`, {
      method: "POST",
      body: JSON.stringify(vote)
    }),

  update: (voteId: number, vote_update: VoteUpdate): Promise<ActionResponse<VoteLoad>> =>
    fetchHandler(`/api/v1/vote/update/${voteId}`, {
      method: "PUT",
      body: JSON.stringify(vote_update)
    }),

  delete: (voteId: number): Promise<ActionResponse<void>> =>
    fetchHandler(`/api/v1/vote/delete/${voteId}`, {
      method: "DELETE"
    }),
};
