// This file is auto-generated by a script. Do not edit.

import { fetchHandler } from '@/lib/handlers/apiFetch';
import { ActionResponse } from '@/types/global';
import { type NoneType, VoteDoVote, VoteFind, VoteLoad } from '@/types/vote';

export const apiVote = {
  findVote: (vote: VoteFind): Promise<ActionResponse<VoteLoad>> =>
    fetchHandler(`/api/v1/vote/find-vote`, {
      method: "POST",
      body: JSON.stringify(vote)
    }),

  doVote: (vote: VoteDoVote): Promise<ActionResponse<NoneType>> =>
    fetchHandler(`/api/v1/vote/do-vote`, {
      method: "POST",
      body: JSON.stringify(vote)
    }),
};
