"""Recreate tables

Revision ID: 24b83e7d0343
Revises: 
Create Date: 2025-12-31 17:21:09.264036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '24b83e7d0343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('QUESTION', 'ANSWER', 'TAG', name='actioncontenttype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('VIEW', 'UPVOTE', 'DOWNVOTE', 'BOOKMARK', 'POST', 'EDIT', 'DELETE', 'SEARCH', name='actiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('other_user_id', sa.Integer(), nullable=True),
    sa.Column('other_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['other_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    # ### end Alembic commands ###
