"""Add num_questions to tag

Revision ID: 34c308381e2a
Revises: 7c0708eb27e6
Create Date: 2025-11-05 18:32:13.860417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '34c308381e2a'
down_revision: Union[str, Sequence[str], None] = '7c0708eb27e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('num_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'num_questions')
    # ### end Alembic commands ###
