"""Update account model to make the combination of provide_account_id and username unique

Revision ID: 4157c1b3f243
Revises: b0d97e8c72f1
Create Date: 2025-11-07 21:15:51.387181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4157c1b3f243'
down_revision: Union[str, Sequence[str], None] = 'b0d97e8c72f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provider_account_id_username', ['provider_account_id', 'username'])

    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.drop_column('id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_account_id_username', type_='unique')
    # ### end Alembic commands ###
