"""Account model update

Revision ID: 6feecbfbb769
Revises: ef7fbb9d2409
Create Date: 2025-11-04 21:42:55.027383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6feecbfbb769'
down_revision: Union[str, Sequence[str], None] = 'ef7fbb9d2409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('account', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.alter_column('account', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('account', 'image')
    # ### end Alembic commands ###
