"""Add relationship to Tag and Question

Revision ID: 6ff8a7be92e3
Revises: d98e112cafd6
Create Date: 2025-11-05 17:53:19.723708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ff8a7be92e3'
down_revision: Union[str, Sequence[str], None] = 'd98e112cafd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
