"""Add relationship between user, questions, and answers

Revision ID: 7c0708eb27e6
Revises: 6ff8a7be92e3
Create Date: 2025-11-05 18:28:06.134974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7c0708eb27e6'
down_revision: Union[str, Sequence[str], None] = '6ff8a7be92e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('answer', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer', sa.VARCHAR(), nullable=False))
    op.drop_column('answer', 'content')
    # ### end Alembic commands ###
