# THIS FILE IS AUTO-GENERATED BY THE 'generate_settings.py' CLI TOOL.
# DO NOT EDIT THIS FILE MANUALLY.
#
# You can modify the generated file, but be aware that re-running the tool
# will overwrite your changes.

from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Any, List


class Settings(BaseSettings):
    DATABASE_URL: str
    DEV_MODE: bool
    ALLOW_ORIGINS: list

    model_config = SettingsConfigDict(
        env_file='.env',
        env_file_encoding='utf-8',
        extra='ignore',
    )


settings = Settings()
